### ISSUE TITLE
Cannot install to Cache 2017.2

### ISSUE THREAD

**Issue by davidpeterunderhill** [intersystems-community/webterminal#113]
Installing to Cache 2017.2 results in import errors as below

![image](https://user-images.githubusercontent.com/36628548/40114176-d4088304-5903-11e8-80c6-84df9c926652.png)

Is there a release that is compatible or something I need to do to get this to work?

**Comment by eduard93** [comment]
Unable to reproduce on:
`Cache for Windows (x86-64) 2017.2.1 (Build 801U) Wed Dec 6 2017 09:07:51 EST`

Please try importing via:
`do $system.OBJ.Load(file, "ck")

**Comment by eduard93** [comment]
Closed due to inactivity
