### ISSUE TITLE
Install errors on InterSystems IRIS

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/webterminal#115]
Currently erros on IRIS:

`set mapTo = $LISTBUILD("%All")`

and
```
        set Properties("Globals") = "IRISTEMP"
        set Properties("Library") = "IRISLIB"
        set Properties("Routines") = "IRISTEMP"
        set Properties("SysGlobals") = "IRISSYS"
        set Properties("SysRoutines") = "IRISSYS"
        set Properties("TempGlobals") = "IRISTEMP"
```

**Comment by ZitRos** [comment]
I've tested the latest installation on IRIS, it run well. Can you provide more information on errors you have?

**Comment by eduard93** [comment]
Seems I'm on a old release. I'll try with a latest one.

**Comment by eduard93** [comment]
I got  v3.2.2 from GitHub and it's old.
Please update GitHUb release

**Comment by ZitRos** [comment]
Haven't you noticed the latest release was on Jan 6, 2016? 😄 
Updated and referenced the project web page for further updates. Thanks Edward for pointing on this.

**Comment by eduard93** [comment]
I usually gust grab latest release.

**Comment by eduard93** [comment]
Thank you!
