### ISSUE TITLE
<CLASS DOES NOT EXIST>zCreateProjection+36^WebTerminal.Installer.1 *WebTerminal.Analytics

### ISSUE THREAD

**Issue by interhealth** [intersystems-community/webterminal#119]
WebTerminal-v4.8.0.xml

running on:
Cache for UNIX (Red Hat Enterprise Linux for x86-64) 2017.2.1 (Build 801_3_18583U) Tue Nov 27 2018 06:12:01 EST [HealthShare Modules:Core:15.03.9903 + Linkage Engine:15.03.9903]

this line of code:
do ##class(WebTerminal.Analytics).ReportInstallStatus(err)

causes this error:
<CLASS DOES NOT EXIST>zCreateProjection+36^WebTerminal.Installer.1 *WebTerminal.Analytics

**Comment by ZitRos** [comment]
Hello! Thanks.

Many people has reported this issue but no one helped me to investigate what's wrong...

Could you please try/answer the following:
0. Import XML and does not compile (untick "compile" in the import popup).
1. Try to compile all classes in WebTerminal package manually. Does it compiles normally?
2. Try to compile WebTerminal.Analytics class, and then WebTerminal.Installer class. Does it work now?

**Comment by interhealth** [comment]
The analytics class compiles OK by itself.
The project imports without compiling OK.
The installer class does not compile

**Comment by ZitRos** [comment]
Really interesting. You compile WebTerminal.Analytics class on its own, and
then the error says that no WebTerminal.Analytics class is found. I wish I
could play around with your InterSystems setup to find out what is causing
this error to happen. Well, if you are a tech person I would appreciate you
trying to figure this out :)

As a quick workaround to make it work, you can comment out that erroring
line in WebTerminal.Installer class. However, it is much more interesting
to dig in and find out the root case of this problem, as I have never had a
chance to reproduce it...

Thanks you.

**Comment by ZitRos** [comment]
All right, now I've finally found [an instance](https://hub.docker.com/_/intersystems-iris-data-platform/plans/222f869e-567c-4928-b572-eb6a29706fbd?tab=instructions) where this problem is reproducible.

Furthermore, I've found a source of the problem. Expect the update soon! Again, thanks for reporting the issue.

**Comment by ZitRos** [comment]
@interhealth, now this issue is fixed! Please confirm that the [latest version](https://intersystems-community.github.io/webterminal/#downloads) (4.8.3) doesn't bring this problem.
Thank you!

**Comment by interhealth** [comment]
Hi Nikita

Fix Confirmed.
Installation completed on 2018.1.1HS.2052.0
Thank you for the followup!

**Comment by ZitRos** [comment]
Awesome! Thanks, @interhealth, for reporting this!
