### ISSUE TITLE
4.8.0: ERROR #5002: Cache error: <METHOD DOES NOT EXIST>zCreateProjection+30^WebTerminal.Installer.1 *GetISCProduct,%SYSTEM.Version

### ISSUE THREAD

**Issue by askurek** [intersystems-community/webterminal#120]
It seems, that WebTerminal.Installer relies on method %SYSTEM.Version.GetISCProduct, but this method does not exist in Cache 2014.1.2.

WebTerminal 4.8.0
$zv = Cache for Windows (x86-64) 2014.1.2 (Build 753_0_14724U) Tue Dec 16 2014 09:18:13 EST

**Comment by ZitRos** [comment]
Good point, thank you!

Were you able to install the terminal by removing this line of code?

**Comment by askurek** [comment]
> 
> 
> Good point, thank you!
> 
> Were you able to install the terminal by removing this line of code?

I was able to install webterminal by "porting" the GetISCProduct method from Cache 2017.1 to 2014.2.1 (I was able to edit and compile SYSTEM.Version class).

**Comment by ZitRos** [comment]
Good. Thank for reporting this, we'll take a note.

**Comment by ZitRos** [comment]
Thanks, @askurek! Now this issue should be fixed. Please confirm that the [latest version](https://intersystems-community.github.io/webterminal/#downloads) (4.8.3) doesn't bring this problem.
Thank you!
