### ISSUE TITLE
Copy/Paste Issue

### ISSUE THREAD

**Issue by mebays** [intersystems-community/webterminal#121]
USER > w $zv
Cache for UNIX (Red Hat Enterprise Linux for x86-64) 2017.1.3 (Build 317_0_18201U) Tue Jul 17 2018 16:13:49 EDT

USER > /info
Caché WEB Terminal v4.7.4
Author:                        Nikita Savchenko (ZitRo)
Project:                       Homepage
Documentation:                 On the project's homepage
Repository:                    GitHub
Bug/Feature Tracker:           GitHub
2013-2019 © Nikita Savchenko

When copy and paste from a windows notepad it indents line rather than executing the return as expected.

Notepad Input:
set obj = {}
set obj.Test = "test1"
set obj.TestTwo = "test2

Screen shot of the paste:
![image](https://user-images.githubusercontent.com/11648127/53838518-4bf26600-3f63-11e9-826a-e77a2be1e0e4.png)

**Comment by ZitRos** [comment]
It's hard to argue that this should be a standard terminal behavior. However, implementing such thing in WebTerminal is quite tricky. I am assigning a feature label here hoping that one day this will be prioritized, as the project is not actively maintained right now.

Thank you!

**Comment by ZitRos** [comment]
@mebays, so I managed this in a quick way: all newlines are replaced now by a single space character. This improves copying/pasting and resolves your issue. Thanks!
