### ISSUE TITLE
Duplicate Role error

### ISSUE THREAD

**Issue by pisani** [intersystems-community/webterminal#122]
If installing using a user that already has the role %DB_IRISSYS, or in the cache version %DB_CACHESYS, then the installation fails with

Creating WEB application "/terminalsocket"...
WEB application "/terminalsocket" is created.
ERROR #878: Duplicate Target role %DB_IRISSYS.
  > ERROR #5090: An error has occurred while creating projection WebTerminal.Installer:Reference.

because cspProperties("MatchRoles") contains this role twice, eg - ":%DB_IRISSYS:%DB_IRISSYS"

**Comment by ZitRos** [comment]
This is an awesome finding, thank you @pisani! We'll try to incorporate the fix as soon as we can - but please take a note that this project currently is not actively maintained.

**Comment by ZitRos** [comment]
Thanks @pisani! Now this issue should be fixed. Please confirm that the [latest version](https://intersystems-community.github.io/webterminal/#downloads) (4.8.3) doesn't bring this problem.
Thank you!
