### ISSUE TITLE
Small change and a question

### ISSUE THREAD

**Issue by joelsolon** [intersystems-community/webterminal#127]
Small change: please change COS to ObjectScript in the help for /sql (and anywhere else).

Question: why is there a space between the namespace and the >?
USER > instead of USER>

**Comment by ZitRos** [comment]
Hello @joelsolon! Glad to hear from you!

> Small change: please change COS to ObjectScript in the help for /sql (and anywhere else).

Noted. Will fix it within a couple of days (possibly today).

> Question: why is there a space between the namespace and the >?

This is just an aesthetic question. From the very beginning of development, I thought that if there is a space after `>`, why not to add a space beforehand as well. As well as, for example, some terminal emulators replace this `>` symbol to something else at all (like `λ`). Are there any reasons not to add this space?

**Comment by joelsolon** [comment]
Your comment above reminded me that my real question is: "why is there a space **after** the >?" Because a space **after** the > in InterSystems Terminal has a special meaning!

If training or certification materials show a screenshot from WebTerminal that looks like this:
`USER > set x = 4`
a reader using InterSystems Terminal might think that they should type a space before the set statement, and they won't understand why their statement didn't actually set x.
It looks like it's not a problem the other way, because WebTerminal ignores any leading spaces before a statement. And it looks like WebTerminal doesn't support the **ancient** form of writing a routine this way, using ZI, ZL, ZS commands.

**Comment by ZitRos** [comment]
Interesting.

You right, in WebTerminal, the space character goes **before and after** `>` symbol. But, on the other hand, if we change it now, WebTerminal users will be confused. I wouldn't call it even an issue to be honest. Even though spaces do matter in ObjectScript 🤗

Regarding the ancient form of writing routines, yep, that's true until we find something better than [using xecute under the hood](https://github.com/intersystems-community/webterminal/blob/4d6dc00c9e1c166a3f9b63092dd722812c4b98d5/src/cls/WebTerminal/Core.cls#L349) in the core of WebTerminal, it won't support `ZI, ZL, ZS commands`, as well as some other core features (like [$ZA and $ZB variables](https://github.com/intersystems-community/webterminal/issues/92)).

**Comment by joelsolon** [comment]
I agree; it's not an issue. It was a question added as part of an issue that almost became an issue on its own ;-). I wouldn't bother changing it now, only to support `ZI, ZL, ZS`.

**Comment by ZitRos** [comment]
Fixed in WebTerminal v4.9.0 along with adding `call` support in `/sql`. Cheers!

**Comment by ZitRos** [comment]
@joelsolon, fixed in WebTerminal v4.9.0 along with adding `call` support in `/sql`. Cheers!
