### ISSUE TITLE
refusing from /terminalsocket

### ISSUE THREAD

**Issue by daimor** [intersystems-community/webterminal#131]
Since the last few versions, it is possible to call `%CSP.WebSocket` from `%CSP.REST`.
As an example you can look at `%API.Atelier.v1` method `RunDebugger` It redirects access to `%Atelier.v1.XDebugAgent` which in fact is WebSocket.

**Comment by ZitRos** [comment]
Hello Dima! Thanks!

But at least we need to leave `/terminalsocket` for the previous versions, right?

**Comment by daimor** [comment]
Depends on how much old version you would like to support. I suggest, that this way available at least since 2016.2 where API Atelier was appereared.

**Comment by ZitRos** [comment]
As far as I remember, WebTerminal is compatible with 2014.1+. So I think it would be a downgrade which isn't worth a change.

**Comment by daimor** [comment]
Your analytics collects information about Caché version where installed?

**Comment by ZitRos** [comment]
Unfortunately, no. Only the WebTerminal version and install status (any errors) are collected.

But anyway, if we compare the pros and cons of this change, there are no pros in implementing it (in usability), whereas there are cons of cutting two release versions.

**Comment by ZitRos** [comment]
So should we close it?

**Comment by daimor** [comment]
As you wish, I would implement both ways, at least would added socket endpoint to Router.
Least supported version is [2016.1](https://cedocs.intersystems.com/ens20161/csp/documatic/%25CSP.Documatic.cls?PAGE=CLASS&LIBRARY=%25SYS&CLASSNAME=%25CSP.WebSocket) 
Any versions less, quite old already, when you are going to drop those versions?
You still use `%ZEN.Auxiliary.jsonProvider`, if you drop support for such an old version, you can make it work faster with native JSON support.

**Comment by ZitRos** [comment]
For sure, but I know which pain can it cause if anyone still uses v2015 for
example. During my last training I saw people having Healthshare 2015.

Nikita

**Comment by ZitRos** [comment]
@daimor 
Yup, it turned out that WebTerminal collects ISC Product version indeed
So there are 17 installs out of 173 recorded for a couple of last months which use InterSystems products of version 2015 and lower.

**Comment by ZitRos** [comment]
~2,5% of users, still, something I wouldn't drop in favor of just updating things.
