### ISSUE TITLE
Broken on IRIS 2020

### ISSUE THREAD

**Issue by ZitRos** [intersystems-community/webterminal#133]
This issue is reported by InterSystems customer, who love WebTerminal and are having problems installing it on IRISHealth 2020 (Developer download).

Server: RedHat Linux
Instance: CWTv4.9.2 *:IRISHEALTH:*

As reported, also doesn't work on windowsPC.

**Comment by rajrsingh** [comment]
@ZitRos is this fixed by this commit and all that needs to be done is a new release? https://github.com/intersystems-community/webterminal/commit/8b803e6650dbc22b0d88ff24ed4fcccb1808acee

**Comment by ZitRos** [comment]
@rajrsingh hm, indeed. I didn't test this on IRIS 2020 by the way. If it works for you then yes, it's just a matter of releasing a new version.

Let me check this weekend, thanks!

**Comment by rajrsingh** [comment]
Hi @ZitRos we have checked it with IRIS 2020 and it works.

**Comment by ZitRos** [comment]
[v4.9.3](https://intersystems-community.github.io/webterminal/#downloads) is now ready! @rajrsingh 
 thanks for pointing out to what was the cause.
