### ISSUE TITLE
Last releases don't work for me in 2020.1

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/webterminal#136]
I've installed versions 4.9.2 and 4.9.3 in 2020.1... and it don't work...It's continuosly claiming that the the connection is lost... in 2019.1 it works.

![image](https://user-images.githubusercontent.com/6997495/82238012-e192cf00-9936-11ea-9a68-e4a334ece62f.png)

**Comment by ZitRos** [comment]
Thanks for reporting! It's fun, every new ISC product version breaks something in WebTerminal for the past 4 years in a row.

Will take a look later this week.

**Comment by ZitRos** [comment]
Just tested `WebTerminal-v4.9.3` with both `iris-community:2020.2.0.204.0` and `iris-community:2020.1.0.215.0` Docker containers. It works.

If it's still actual, please clarify:
+ Your `$ZV`
+ Do you have any load balancers or proxies in front of IRIS? (they may not route WebSockets well)

**Comment by zhaancampbell** [comment]
Hi,

We only have 1 Apache with CSP gateway in front of the DB.
Cache for UNIX (Oracle Solaris for x86-64) 2018.1.2 (Build 309_5_19235U) Thu Aug 22 2019 14:50:54 EDT

[cid:image001.png@01D637E5.F897BA60]<https://www.qlink.co.za/QLHome/site_terms_conditions.php>

**Comment by jtsalten** [comment]
Hi Nikita,
I've retested again in 2020.1 after uninstall it manually and reinstalling again from xml files and it works.
I think my issue was related to ZPM... I've realized that ZPM fails with using Spanish Locale...(I already reported that)... not sure if it's that but it's the only thing that I can think of.
Anyway, regarding WebTerminal 4.9.3... for me v4.9.3 it works in IRIS 2020.1

**Comment by ZitRos** [comment]
Glad to hear it's working! Thanks for investigating. You can file an issue in [ZPM's repo](https://github.com/intersystems-community/zpm), guys actively develop it right now.
