### ISSUE TITLE
HealthShare Install Fails - iscProductVersion relying on %SYSTEM.Version:GetISCProduct()>=4 needs to be updated.

### ISSUE THREAD

**Issue by tanifgit** [intersystems-community/webterminal#141]
When installing on an InterSystems IRIS-based HealthShare (Health Connect) instance the installation fails due to trying to use a CACHE-oriented role.
The error is: ERROR #879: Target role %DB_CACHESYS does not exist.
This happens because the check in the code uses %SYSTEM.Version:GetISCProduct()
This would return 3 for HealthShare and 4 for InterSystems IRIS.
And the code assume IRIS-oriented resource only if #iscProductVersion >= 4, but for an IRIS-based HealthShare this breaks.

So the check should be different (perhaps also using the actual version, e.g. >2019 or something else).

**Comment by ZitRos** [comment]
Hello! Thank you for reporting this.

Is there any reliable way to determine that it is HealthShare product? Any
pull request you will be able to make is very welcome.

Nikita
