### ISSUE TITLE
Switch from /terminal to /terminalsocket assumes that /terminal was at the root of the URL

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/webterminal#142]
https://github.com/intersystems-community/webterminal/blob/c49b0ac1d2a98c6084598bcf1a65ce794a13b89e/src/client/js/server/index.js#L56-L61

This fails in a situation where a "real" web server is hosting Web Gateway connections to multiple InterSystems servers. For instance an IIS instance on a server named `webhost` configured with root applications `dev` and `test`, and the Web Gateway connecting `/dev` and `/test` URLs to different InterSystems servers.

The WebTerminal URL for the dev server would be `http://webhost/dev/terminal/` but the code above points the websocket to `ws://webhost/terminalsocket/WebTerminal.Engine.cls`

**Comment by ZitRos** [comment]
Hello! Thanks for reporting this issue.

I'm not maintaining this project right now - however I would gladly accept any pull request you can make. If you could also [export the XML](https://github.com/intersystems-community/webterminal#webterminal-project-development) from any prior-IRIS installation, I can then release it via official channels.

I am not very sure how environments work, but it seems to be easy to fix, as far as I understand:

```diff
 function getNewWs () { 
     return new WebSocket(`${ (location.protocol === "https:" ? "wss:" : "ws:") 
         }//${ location.hostname }:${ location.port || 
         (location.protocol === "https:" ? "443" : "80") 
-         }/terminalsocket/${ encodeURIComponent(CACHE_CLASS_NAME) }`); 
+         }${ location.pathname.includes('/terminal') ?  location.pathname.replace(/\/terminal.*/, "/terminalsocket") : "/terminalsocket" }/${ encodeURIComponent(CACHE_CLASS_NAME) }`); 
 } 
```

**Comment by gjsjohnmurray** [comment]
@ZitRos I have submitted PR #147 to resolve this.
