### ISSUE TITLE
WebTerminal lost connection with server (code 1006)

### ISSUE THREAD

**Issue by jpontois** [intersystems-community/webterminal#148]
Hi,

I have a problem with the recent update 4.9.4 of the WebTerminal.

This message appeared after the loading of the page :

```
New update is available. Click here to install it now. Changelist:
4.9.4: No longer require /terminal to be at the root of the URL
```

So I installed the new version. Unfortunatly, after refreshing the page, I have this message again and again :

```
WebTerminal lost connection with server (code 1006).
Attempting to restore session in 10 seconds...
Please, refresh the web page to start a new session.

WebTerminal lost connection with server (code 1006).
Attempting to restore session in 10 seconds...
```

I tried to reinstall the previous version we were using, the 4.9.3, but it doesn't solve the problem (I also tried the 4.9.2, but same result).

The web application under System Administration -> Security -> Applications -> Web Applications seems to be identical to the one on another environment that work from the WebTerminal perspective.

It seems to be a setting issue, but I don't know where to look at. I don't know if this is a bug or a if something isn't right in my parameters, but I thought you might be interested by this behavior.

And if someone has an idea on how to solve this, I could use it :D

**Comment by gjsjohnmurray** [comment]
When comparing between an environment that works and the one that doesn't, did you also check the settings of the /terminalsocket application? If not, please do that.

**Comment by jpontois** [comment]
Yes, they are identical

**Comment by gjsjohnmurray** [comment]
Have you restarted the IRIS environment since the problem appeared? If not, please do this. #143 is a similar issue and the OP says a restart sometimes resolves it. Maybe yours isn't related to the 4.9.4 update.

**Comment by jpontois** [comment]
We just did, and it still doesn't solve the problem :/

**Comment by gjsjohnmurray** [comment]
When you downgraded to 4.9.3 did you import the XML using an account that holds the %All role? I don't know whether that would make a difference. I'm puzzled that the 4.9.4 upgrade could have broken WebTerminal so comprehensively on this one environment.

What is the $ZV string?

On DC you reported that you don't seem to have run out of licenses. Did you review the License Usage page on System Operation section of Portal? And also the Web Sessions page?

**Comment by jpontois** [comment]
Yes, the account on which I did the downgrade have the %All role.

$zv : IRIS for Windows (x86-64) 2021.1 (Build 215U) Wed Jun 9 2021 09:39:22 EDT

What I posted on the DC is the table you find at System Operation -> License Usage
I don't know what is the System Operation section of Portal or the Web Sessions page. Where can I find these informations ?

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/177337577-b5153886-430b-4373-9239-b02a4947abda.png)

**Comment by gjsjohnmurray** [comment]
According to https://community.intersystems.com/post/web-teminal-lost-connection-server-code-1006#comment-194696 the underlying cause was that the UnknownUser account didn't have %DB_IRISLIB:R permission.

@ZitRos I think this issue can be closed.
