### ISSUE TITLE
WebTerminal not working on IRIS Health 2024.2

### ISSUE THREAD

**Issue by lauracysnet** [intersystems-community/webterminal#155]
I've been using web terminal last years and I wanted to use it in my new instance IRIS Health 2024.2.

I have it in container, with a webgateway. I have imported Web Terminal version 4.9.5 and it works fine. But when I try to connect to terminal I have this error:
![Captura de pantalla 2024-08-06 a las 10 00 30](https://github.com/user-attachments/assets/b9977e59-23b7-4fdc-afcc-9d3dcb48a3ad)

In webgateway log I have this error:
`2024-08-06 10:01:27 192.168.65.1 - - [06/Aug/2024:08:01:26 +0000] "GET /terminal/ HTTP/1.1" 404 188 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
`
And in audit database I have this one:
```
Description:  /terminal login failure
Timestamp:    2024-08-06 08:01:26.729   Username:     UnknownUser
UTCTimestamp: 2024-08-06 08:01:26.729   Pid:          924
Event Source: %System                   JobId/JobNum: 196621/13
Event Type:   %Login                    Session ID:   SveISPXkSH
Event:        LoginFailure              IPAddress:    192.168.65.1
System ID:    irishealth:IRIS           Executable:   CSPa24.so
Namespace:    %SYS                      Index:        1576
Roles:        
User Info:                              O/S User:     CSP Gateway
Routine:      
Authentication: Unauthenticated
StartupClientIPAddress: 172.23.0.3
Event Data:
Error message:      ERROR #864: An authenticated user name is required.
Web Application:    /terminal
$I:                 |TCP|1972|924
$P:                 |TCP|1972|924

```
I have tried to pass user &password via URL, and then I have this:
![Captura de pantalla 2024-08-06 a las 10 02 46](https://github.com/user-attachments/assets/f032aa6f-4468-4171-a897-8717f08ee04e)

In webgateway log I have this:

```
2024-08-06 10:02:38 192.168.65.1 - - [06/Aug/2024:08:02:36 +0000] "GET /terminal/?IRISUserName=_SYSTEM&IRISPassword=XXX HTTP/1.1" 200 888 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
2024-08-06 10:02:38 192.168.65.1 - - [06/Aug/2024:08:02:36 +0000] "GET /terminal/css/index.css HTTP/1.1" 404 188 "http://localhost:8880/terminal/?IRISUserName=_SYSTEM&IRISPassword=XXX" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
2024-08-06 10:02:38 192.168.65.1 - - [06/Aug/2024:08:02:36 +0000] "GET /terminal/js/index.js HTTP/1.1" 404 188 "http://localhost:8880/terminal/?IRISUserName=_SYSTEM&IRISPassword=XXX" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"

```
I don't know what else I can do. I have checked web application configuration comparing it with another instance that I have (IRIS health community 2023.3), but I don't see any difference...

Any help?

**Comment by nikitaeverywhere** [comment]
Hi! Can you screenshot your web application configuration?

What else can you try that can help: re-compiling the WebTerminal package from Studio, or re-importing it. When importing XML into your env, read the logs - there might be something notable, as WebTerminal tries to install itself on import.

**Comment by gjsjohnmurray** [comment]
I have started investigating what has changed between 2024.1 and 2024.2

Using a Docker container running the 2024.1 community edition (containers.intersystems.com/intersystems/iris-community:2024.1) the initial request `/terminal/` receives a 401 Unauthorized response with a www-authenticate: Basic header

![image](https://github.com/user-attachments/assets/5849b170-a643-409d-ac10-8a5721f2aa90)

This will trigger the web browser to prompt for credentials which it puts into an `Authorization: Basic xxxx` header when it re-requests `/terminal/`

For comparison, here's how 2024.2 (containers.intersystems.com/intersystems/iris-community:2024.2) responds:

![image](https://github.com/user-attachments/assets/63e1736e-24c6-4c2a-8f3d-788fd558f255)

**Comment by gjsjohnmurray** [comment]
I have opened WRC 990183 about this.

**Comment by gjsjohnmurray** [comment]
The WRC response:

A recent change (DP-432503) introduced in 2024.2.0 (CD release) is causing this.

That change now requires that the CSPSystem user have at least READ permissions on the database hosting the REST dispatch class. (-> Workaround)


For cases where that is not true a <PROTECT> error is raised but a side effect is that an HTTP 404 status is returned to the caller instead of the expected HTTP 401.

We already fixed this in 2024.3+ with the following change:

DP-432898 / ALI048 : REST Login endpoints to return 401 HTTP error instead of 404

**Comment by gjsjohnmurray** [comment]
In the case of WebTerminal, the UnknownUser will also need READ permissions on the database,

**Comment by lauracysnet** [comment]
Thank you very much for your time! I couldn't send you the information you requested, sorry.

So the problem it's a bug.. ok. I have tested what you said (assigning READ permission to CSPSystem and UnknownUser) and now it prompt's for credentials.

Thanks again!

**Comment by gjsjohnmurray** [comment]
@lauracysnet I'm glad this solved it for you.

I have just posted https://community.intersystems.com/post/webterminal-broken-iris-20242 for the benefit of the wider community.

@nikitaeverywhere I think this issue can be closed here.

**Comment by nikitaeverywhere** [comment]
> @nikitaeverywhere I think this issue can be closed here.

Great, thanks for help!
