### ISSUE TITLE
Rewrite autocomplete mechanism

### ISSUE THREAD

**Issue by ZitRos** [intersystems-community/webterminal#58]
Current autocomplete mechanism does not use a lot of useful features so it has to be rewritten:
1. No inline autocomplete: `set cls = ##class(...).%New()` `write cls.<Nothing here>`
2. No private/public method/classmethod classification: `do ##class(...).Method` - incorrect, because `Method` is not ClassMethod;
3. No inherited methods/properties/etc - implementing this over current autocomplete tactics would just overlap browser storage which is limited (5MB for FF, 10 for GC, etc) and also decrease performance;
4. Etc.

ToDo list:
- [x] Rewrite basic autocomplete lexical mechanism;
- [x] Replace static one-time generated AC with dynamic loaded AC;
- [x] Suggesting class names;
- [x] Support for class constructions: `do ##class(...).<suggest>`;
- [x] Associating variable name with class type assigned to it;
- [x] Support for variable constructions: `set a = ##class(...).%New()` -> `write a.<suggest>`;
- [x] ClassMethods support;
- [x] Properties/Parameters support;
- [x] ClassMethods differ from Methods and private methods support;
- [x] Routine support;
- [ ] Support of recursive reference constructions: `write a.Methods.<suggest>`;

[ Subject to be updated ]

**Comment by eduard93** [comment]
>Support of recursive reference constructions: `write a.Methods.<suggest>;`

Maybe `write a.Property.<suggest>`?
Support of  `write a.Method().<suggest>;` is whole other much more difficult issue (well, parse returntype of method definition really)

**Comment by ZitRos** [comment]
> Maybe write a.Property.<suggest>?

I meant a list under `Methods`: `write a.Methods.Count()`.

**Comment by ZitRos** [comment]
Making a progress on this. Pretty complete COS parser state-machine mechanism is designed, there are three more steps left: complete engine, autocomplete and highlight based on the grammar, and the complete grammar. e638b32
![img_3318](https://cloud.githubusercontent.com/assets/4989256/17534353/79c4132c-5e91-11e6-8db6-f9cdb5b9d338.JPG)
![img_3324](https://cloud.githubusercontent.com/assets/4989256/17534354/7a81febe-5e91-11e6-848d-7753193c210c.JPG)
![image](https://cloud.githubusercontent.com/assets/4989256/17534391/a9d5987e-5e91-11e6-9b09-5056acbce4ed.jpg)

**Comment by ZitRos** [comment]
This semantic code, which describe the rules:
![2016-08-10_003648](https://cloud.githubusercontent.com/assets/4989256/17534596/88186e18-5e92-11e6-8993-e7bfac6dd1d0.png)
Is turned to this table of states:
![2016-08-10_002022](https://cloud.githubusercontent.com/assets/4989256/17534554/65023d3c-5e92-11e6-92c6-16c40a495118.png)
And evaluated later:
![2016-08-10_002043](https://cloud.githubusercontent.com/assets/4989256/17534555/65083354-5e92-11e6-9fbc-dacd7566b7e7.png)
This will allow WebTerminal to know and predict what user enters.

**Comment by ZitRos** [comment]
Rewrite was done without recursive reference resolution and can be considered complete.
